# ===================================================================
# COMMON SPRING BOOT PROPERTIES
#
# This sample file is provided as a guideline. Do NOT copy it in its
# entirety to your own application.               ^^^
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# IDENTITY (ContextIdApplicationContextInitializer)
spring:
    application:
        name:SampleGradleProject

mybatis:
    url: jdbc:
    driverClassName: com.mysql.jdbc.Driver
    userName:
    password: